### ISSUE TITLE
controller report action refactor

### ISSUE THREAD

**Issue by rngtng** [schmurfy/dav4rack_ext#4]
I just read https://github.com/chrisroberts/dav4rack/issues/45 and wanted to add my thoughts here (as it's more extension related). 

What 'tools' do you need within the resource for the response? 

I'm still reading through the code, but first impression is that values for `href` and `props` should sit on resource, then you could do sth like:

``` ruby
hrefs = resource.report_resources(request_document)
props = resource.report_props(request_document)

multistatus do |xml|
  hrefs.each do |_href, cur_resource|
    xml.response do
      xml.href _href

      if cur_resource && cur_resource.exist?
        propstats(xml, get_properties(cur_resource, props))
      else
        xml.status "#{http_version} #{NotFound.status_line}"
      end

    end
  end
end
```

does this help?

**Comment by n-rodriguez** [comment]
> The more I worked with the codebase the more I feel like controllers and resources should be the same entity

Yes : https://github.com/georgi/rack_dav#implementing-your-own-webdav-resource

**Comment by schmurfy** [comment]
Thanks for your inputs but I am not sure how rack_dav and dav4rack relate to each other now since the later was forked from the first, anyway as I mentioned I already tried once to work on that but lost my harddrive which crushed my will to push further, until now at least.

**Comment by n-rodriguez** [comment]
> anyway as I mentioned I already tried once to work on that but lost my harddrive which crushed my will to push further, until now at least.

ouch... very bad trip :/ 

Well I also tried to play with dav4rack to implement a Caldav server within Rails and get some [results](https://github.com/jbox-web/cervicale) but I stopped by lack of time. Now I'm getting on this again and try to think about a new implementation.
